definitions:
  main.DoCallback:
    properties:
      amount:
        type: string
      currency:
        type: string
      mermsisdn:
        type: string
      partnID:
        type: string
      resultCode:
        type: string
      resultDesc:
        type: string
      subsmsisdn:
        type: string
      transid:
        type: string
    type: object
  main.DoCallbackResponse:
    properties:
      PartnID:
        type: string
      ResultCode:
        type: string
      ResultDesc:
        type: string
    type: object
  main.DoCheckTrans:
    properties:
      mermsisdn:
        type: string
      partnID:
        type: string
      transid:
        type: string
    type: object
  main.DoCheckTransResponse:
    properties:
      ResultCode:
        type: string
      ResultDesc:
        type: string
      TransID:
        type: string
    type: object
  main.DoM2M:
    properties:
      amount:
        type: string
      currency:
        type: string
      mermsisdn1:
        type: string
      mermsisdn2:
        type: string
      partnID:
        type: string
      transid:
        type: string
    type: object
  main.DoM2MResponse:
    properties:
      PartnID:
        type: string
      ResultCode:
        type: string
      ResultDesc:
        type: string
      SystemID:
        type: string
      TransID:
        type: string
    type: object
  main.DoM2S:
    properties:
      amount:
        type: string
      currency:
        type: string
      mermsisdn:
        type: string
      partnID:
        type: string
      subsmsisdn:
        type: string
      transid:
        type: string
    type: object
  main.DoM2SResponse:
    properties:
      PartnID:
        type: string
      ResultCode:
        type: string
      ResultDesc:
        type: string
      SystemID:
        type: string
      TransID:
        type: string
    type: object
  main.DoS2M:
    properties:
      amount:
        type: string
      callbackurl:
        type: string
      currency:
        type: string
      mermsisdn:
        type: string
      messageS2m:
        type: string
      partnID:
        type: string
      subsmsisdn:
        type: string
      transid:
        type: string
    type: object
  main.DoS2MResponse:
    properties:
      PartnID:
        type: string
      ResultCode:
        type: string
      ResultDesc:
        type: string
      SystemID:
        type: string
      TransID:
        type: string
    type: object
  main.SendSMS:
    properties:
      flash:
        type: string
      message:
        type: string
      msisdn:
        type: string
      partnID:
        type: string
      partnName:
        type: string
      sender:
        type: string
    type: object
  main.SendSMSResponse:
    properties:
      Message:
        type: string
      Resultdesc:
        type: string
      Resutcode:
        type: string
    type: object
  main.TcheckBal:
    properties:
      currency:
        type: string
      partnID:
        type: string
      subsmsisdn:
        type: string
      transid:
        type: string
    type: object
  main.TcheckBalResponse:
    properties:
      Balance:
        type: string
      PartnID:
        type: string
      ResultCode:
        type: string
      ResultDesc:
        type: string
      TransID:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/docallback:
    post:
      consumes:
      - application/json
      description: Accept a callback request
      parameters:
      - description: DoCallback
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.DoCallback'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.DoCallbackResponse'
      summary: Accept a callback request
      tags:
      - Callbacks
  /api/v1/dochecktrans:
    post:
      consumes:
      - application/json
      description: Check the balance of a specified account.
      parameters:
      - description: DoCheckTrans
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.DoCheckTrans'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.DoCheckTransResponse'
      summary: Do a Check Balance transaction.
      tags:
      - CheckTransaction
  /api/v1/dom2m:
    post:
      consumes:
      - application/json
      description: Perform a Merchant to Merchant Transaction.
      parameters:
      - description: DoM2M
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.DoM2M'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.DoM2MResponse'
      summary: Do M2M Transaction
      tags:
      - B2B
  /api/v1/dom2s:
    post:
      consumes:
      - application/json
      description: Perform a Merchant to Subscriber transaction.
      parameters:
      - description: DoM2S
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.DoM2S'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.DoM2SResponse'
      summary: Do M2S Transaction.
      tags:
      - B2C
  /api/v1/dos2m:
    post:
      consumes:
      - application/json
      description: Perform a Subscriber to Merchant Transaction
      parameters:
      - description: DoS2M
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.DoS2M'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.DoS2MResponse'
      summary: Do an S2M transaction.
      tags:
      - C2B
  /api/v1/sendsms:
    post:
      consumes:
      - application/json
      description: Send an SMS to a Subscriber.
      parameters:
      - description: SendSMS
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.SendSMS'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.SendSMSResponse'
      summary: Send an SMS
      tags:
      - SendSMS
  /api/v1/tcheckbal:
    post:
      consumes:
      - application/json
      description: Check the balance of a specified account.
      parameters:
      - description: TcheckBal
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.TcheckBal'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.TcheckBalResponse'
      summary: Do a Check Balance transaction.
      tags:
      - Balance
  /swagger.json:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get API Swagger Definition
      tags:
      - internal
swagger: "2.0"
